name: Build PharmaOS Africa APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le projet
        uses: actions/checkout@v4

      - name: Installer Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Installer les dependances
        run: npm ci

      - name: Synchroniser Capacitor
        run: npx cap sync android

      - name: Construire APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Publier APK
        uses: actions/upload-artifact@v4
        with:
          name: PharmaOS-Africa-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
